import logging
import random
import time

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.alert import Alert
from app.models.decision import Decision
from app.models.enrichment import Enrichment
from app.models.enums import AlertStateType, DecisionType, Severity
from app.services.correlation_service import correlate_alert
from app.services.decision_service import make_decision
from app.services.enrichment_service import enrich_ip
from app.services.metrics_service import metrics_store
from app.services.state_service import add_state

logger = logging.getLogger(__name__)

EVENT_TYPES = ["LOGIN_FAILURE", "PORT_SCAN", "MALWARE_BEACON", "PRIV_ESCALATION_ATTEMPT"]
USERS = ["u-1001", "u-1088", "u-2001", "svc-auth", "svc-db"]
IPS = ["185.220.101.4", "103.45.67.89", "62.171.188.15", "198.51.100.22", "192.0.2.101"]


async def generate_random_alert(session: AsyncSession) -> Alert:
    alert = Alert(
        ip_address=random.choice(IPS),
        user_id=random.choice(USERS),
        event_type=random.choice(EVENT_TYPES),
        severity=random.choice([Severity.LOW, Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL]),
    )
    session.add(alert)
    await session.flush()
    await add_state(session, alert.id, AlertStateType.new, "Alert generated by autonomous worker")
    logger.info(
        "alert generated",
        extra={"alert_id": alert.id, "step": "alert_generation", "execution_time_ms": 0},
    )
    return alert


async def process_alert(session: AsyncSession, alert: Alert) -> None:
    start = time.perf_counter()
    try:
        enrich_start = time.perf_counter()
        enrichment_data = await enrich_ip(alert.ip_address)
        enrich_elapsed_ms = (time.perf_counter() - enrich_start) * 1000
        logger.info(
            "enrichment completed",
            extra={"alert_id": alert.id, "step": "enrichment", "execution_time_ms": round(enrich_elapsed_ms, 2)},
        )
        session.add(
            Enrichment(
                alert_id=alert.id,
                reputation_score=enrichment_data["reputation_score"],
                country=enrichment_data["country"],
                isp=enrichment_data["isp"],
                source=enrichment_data["source"],
            )
        )
        await add_state(session, alert.id, AlertStateType.enriched, "Enrichment completed")

        corr_start = time.perf_counter()
        repeated_count = await correlate_alert(session, alert)
        corr_elapsed_ms = (time.perf_counter() - corr_start) * 1000
        logger.info(
            "correlation completed",
            extra={"alert_id": alert.id, "step": "correlation", "execution_time_ms": round(corr_elapsed_ms, 2)},
        )
        decision_payload = make_decision(enrichment_data["reputation_score"], repeated_count)
        session.add(
            Decision(
                alert_id=alert.id,
                decision=DecisionType(decision_payload["decision"]),
                confidence=decision_payload["confidence"],
                reasons=decision_payload["reasons"],
                score=decision_payload["score"],
            )
        )
        await add_state(session, alert.id, AlertStateType.analyzed, "Decision engine completed")
        await session.commit()
        if decision_payload["decision"] == DecisionType.block.value:
            await metrics_store.record_blocked_alert()
        total_elapsed_ms = (time.perf_counter() - start) * 1000
        await metrics_store.record_processing_time(total_elapsed_ms)
        logger.info(
            "alert processed",
            extra={
                "alert_id": alert.id,
                "step": "pipeline_complete",
                "execution_time_ms": round(total_elapsed_ms, 2),
            },
        )
    except Exception:
        await session.rollback()
        await metrics_store.record_failure()
        logger.exception(
            "alert processing failed",
            extra={"alert_id": alert.id, "step": "pipeline_error", "execution_time_ms": 0},
        )
        raise


async def get_severity_distribution(session: AsyncSession) -> dict[str, int]:
    rows = await session.execute(select(Alert.severity))
    distribution: dict[str, int] = {"LOW": 0, "MEDIUM": 0, "HIGH": 0, "CRITICAL": 0}
    for row in rows.scalars().all():
        distribution[row.value] = distribution.get(row.value, 0) + 1
    return distribution
